### ISSUE TITLE
Setup on Raspbian (Raspberry Pi)

### ISSUE THREAD

**Issue by Exzellius** [nitzel/fritzbox-missed-calls-telegram-bot#1]
hey there sorry for the necrophilia on this git but I wanted to ask if you got any expierience on setting this up on raspian?
I'm pretty new to github and python both so it would be wonderful if you could lend me some help :)

Greetings
Exze

**Comment by nitzel** [comment]
Hi Exzellius,
not a problem at all.

Sorry to tell you that I've only ever ran it on a windows machine, but I can't see a reason why it shouldn't work. If you encounter any problems give me a shout or send me an email (you can find it on my profile page, write in German if you prefer) and I might be able to help you out.

nitzel

**Comment by nitzel** [comment]
I'll close this issue for now after half a year, feel free to reopen it or open another one though.
