### ISSUE TITLE
JSON config invalid

### ISSUE THREAD

**Issue by bufemc** [nitzel/fritzbox-missed-calls-telegram-bot#2]
Just in case this repo will get any more updates after 4 years, of if anybody wonders.. There is a small issue. In the config there is a comma after "Suppressed phone number" which makes it invalid JSON. Just remove it.

```
  "phonebook": {
    "None": "Suppressed phone number",
  }
```

The other issue(s) seem to be that although I updated my bot_phonebook.cfg it was not used for CheckCallList .. I have another IP but it still tries to initialize with the default 192.168.178.1.

For a quick & dirty fix you might adjust line 140 in fritzbox.py.

However, got more issues.. so I've given up for the moment..

```
"fritzbox-missed-calls-telegram-bot\fritzbotcallinfo\bot.py", line 48, in __init__
    self.updater.job_queue.put(job_minute, next_t=0.0)
AttributeError: 'JobQueue' object has no attribute 'put'
```

**Comment by nitzel** [comment]
@bufemc Thanks for your feedback. I haven't had access to a FritzBox for a long time now, but fixed the json issue and had a quick look at the error you posted about. Looks like the `put` method was renamed to `_put` so I used the new `run_repeating` instead. Would be great if you could give it a go and let me know if it works now.

**Comment by bufemc** [comment]
Wow, I was quite sure this project is dead after such a long time, so I was quite surprised.
I did pull latest master. Re-adapted my settings in the cfg.

When doing pip install the wished files I get this:
```
ERROR: fritzcollectd 0.7.0 has requirement fritzconnection<1.0.0,>=0.8.0, but you'll have fritzconnection 1.3.0 which is incompatible.
```

And if running example.py I get this:
```
C:\workspace\python\fbox\fritzbox-missed-calls-telegram-bot\fritzbotcallinfo\bot.py:49: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  self.updater = Updater(token=self.telegramToken)
Traceback (most recent call last):
  File "C:/workspace/python/fbox/fritzbox-missed-calls-telegram-bot/example.py", line 6, in <module>
    CI_BOT = CallInfoBot(configFile='bot_phonebook.cfg')
  File "C:\workspace\python\fbox\fritzbox-missed-calls-telegram-bot\fritzbotcallinfo\bot.py", line 68, in __init__
    unknown_handler = CommandHandler(Filters.command, self.cb_unknown)
  File "C:\Python3\lib\site-packages\telegram\ext\commandhandler.py", line 138, in __init__
    self.command = [x.lower() for x in command]
TypeError: '_Command' object is not iterable
```

BTW, not clear is for me what should be set in the upper part of the cfg:
```
  "bot": {
    "clientChatIds": [
    ],
    "telegramToken": "xxx",
    "checkFritzboxInterval": 20
  },
```

for xxx I inserted the API token, but what should go into clientChatIds? I created the bot token as described, but so far no channel (I know how to create such, but not how to connect e.g. the bot with it, yet)..

**Comment by nitzel** [comment]
1)  `ERROR: fritzcollectd 0.7.0 has requirement fritzconnection<1.0.0,>=0.8.0, but you'll have fritzconnection 1.3.0 which is incompatible.` 
I guess you have installed `fritzcollectd` with a dependency on `fritzconnection` no newer than `1.0.0`. Since you invoked `pip` with `--upgrade` you've asked it to install the latest version - which gave a conflict there. Either uninstall `fritzcollectd` or use different [Python Environments](https://docs.python.org/3/tutorial/venv.html) so that you can have the different packages in the correct versions alongside each other.
I've tried the command and in a fresh environment it works fine (Windows10/Anaconda3)

2) `TelegramDeprecationWarning: Old Handler API is deprecated`
I guess I should've specified the versions of the pip packages I was using back then.
There's a [migration guide](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0) but it might be that it's only about adding the `use_context=True` parameter.

3) `clientChatIds`
If I remember correctly, these are the IDs of a chat you have created with the bot. I'd suggest creating a groupchat, adding the bot, and then taking the chat-id from the URL. Should look like this: `https://web.telegram.org/#/im?p=g123` with `g123` being the ID. This was done so that not everyone would be notified by the chatbot, but only certain allowed groups.

Drop me an email if you'd like to discuss anything on Discord or similar.

**Comment by nitzel** [comment]
Ah sorry, this seems to be a way to get a chat ID:
https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id

i.e.
1. Stop your bot
2. Send your bot a command (e.g. `/test`)
2. Load `https://api.telegram.org/bot<YourBOTToken>/getUpdates` in you browser
3. Look for `result[0].message.chat.id` in the returned JSON

I'll update the `Readme.md` once I confirmed all this

**Comment by bufemc** [comment]
Thanks. Read it too late, will try and come back to you soon.

**Comment by bufemc** [comment]
First, for the installation, I re-did if after uninstalling fritzcollectd, and did not use --upgrade (even if it's still in your README ,)) But for comparing the versions, here is the output:

```
pip install requests lxml fritzconnection python-telegram-bot
Requirement already satisfied: requests in c:\python3\lib\site-packages (2.24.0)
Requirement already satisfied: lxml in c:\python3\lib\site-packages (4.5.1)
Requirement already satisfied: fritzconnection in c:\python3\lib\site-packages (1.3.0)
Requirement already satisfied: python-telegram-bot in c:\python3\lib\site-packages (12.7)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python3\lib\site-packages (from requests) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\python3\lib\site-packages (from requests) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python3\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\python3\lib\site-packages (from requests) (2.8)
Requirement already satisfied: cryptography in c:\python3\lib\site-packages (from python-telegram-bot) (2.9.2)
Requirement already satisfied: future>=0.16.0 in c:\python3\lib\site-packages (from python-telegram-bot) (0.18.2)
Requirement already satisfied: tornado>=5.1 in c:\python3\lib\site-packages (from python-telegram-bot) (6.0.4)
Requirement already satisfied: decorator>=4.4.0 in c:\python3\lib\site-packages (from python-telegram-bot) (4.4.2)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\python3\lib\site-packages (from cryptography->python-telegram-bot) (1.14.0)
Requirement already satisfied: six>=1.4.1 in c:\python3\lib\site-packages (from cryptography->python-telegram-bot) (1.15.0)
Requirement already satisfied: pycparser in c:\python3\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography->python-telegram-bot) (2.20)
```

As I see, you added ```use_context=true``` already in bot.py L 49.

So, I also added my bot to a group chat of mine, and extracted the chat id (which is BTW, prefixed with a minus), but still don't know that much about telegram bots (=> maybe improve README?). If I "talk to my bot" via Telegram (via talking to @<bot-name>, is this the correct way?) and do /start nothing happens, if I send /info also.. nothing happens. As said, have no good knowledge about tg bots, yet.

Anyway, when starting example.py I still get:

```
Traceback (most recent call last):
  File "C:/workspace/python/fbox/fritzbox-missed-calls-telegram-bot/example.py", line 6, in <module>
    CI_BOT = CallInfoBot(configFile='bot_phonebook.cfg')
  File "C:\workspace\python\fbox\fritzbox-missed-calls-telegram-bot\fritzbotcallinfo\bot.py", line 68, in __init__
    unknown_handler = CommandHandler(Filters.command, self.cb_unknown)
  File "C:\Python3\lib\site-packages\telegram\ext\commandhandler.py", line 138, in __init__
    self.command = [x.lower() for x in command]
TypeError: '_Command' object is not iterable
```

**Comment by bufemc** [comment]
Just guessing: it seems nowadays a newly created bot via bot father has NO commands at all, is that possible? start/stop/info just seem to be commands every bot has by default, but see later comments, by default there are no other commands assigned.

I tried to debug and find out who is the culprit and the exception in commandhandler.py L138 tries to assign self.command by iterating (!), but I guess the first condition should match better:
```
        if isinstance(command, string_types):
            self.command = [command.lower()]
        else:
            self.command = [x.lower() for x in command]
```

At that time this is how command is set at my side:
![image](https://user-images.githubusercontent.com/18305092/85393853-fa9e2980-b54d-11ea-8d4b-825e4da5806f.png)

**Comment by bufemc** [comment]
So I added via BotFather some pseudo commands:
command1 desc1
command2 desc2

But that didn't help. I debugged again, this time with breakpoint and could see that the code works for the first 3 commands, which are start, stop, info. But crashes again as above, by going again into the else branch with iterating, although it's not iterable. Same issue as in screenshot above, it tries to iterate through a single element: "_CommandOnlyStart"..

I upgraded python-telegram-bot from 12.7 to 12.8, but that didn't help. Can you find out which versions you use for the dependencies, which seem to work? I think it was easy to find out by something like or exactly ```pip freeze > requirements.txt``` and then add this file to the project :)

**Comment by nitzel** [comment]
Hi @bufemc 
Thanks for your feedback.
I've fixed the TelegramBot now.
I'll suggest pulling the latest version. In the `README.MD` I've specified the versions of the dependencies you'll need. Then you should go to `example.py` and set the `mock_fritzbox` parameter to `True`. This will replace the class interacting with the FritzBox with a mock, that just generates random calls, so that you can test the client first.

The readme instructions should be correct again, so just start a chat with the bot and type `/start` to subscribe to new phone calls. Every 20 seconds there's a good chance the bot will report a couple of missed to you, but you can tweak that timespan in the config file.

There were several major breaking changes in how the APIs I used back then are now working, so that took me a good amount of time.

Could you please then check if it works with your FritzBox and let me know how you're getting on?

**Comment by bufemc** [comment]
Hi, great stuff. "Something" seems to work now. And it's even a little bit too chatty. Looks like a demonstration of John Doe's ,) I still have to check tomorrow what exactly it is doing. But at least no syntactial error, for the moment.

**Comment by bufemc** [comment]
So I started it this morning with mock_fritzbox=False.. First I get printed last calls, few with lookups to dasTelefonbuch, Tellows and Tellows Basic (?) [all 3 always with "not found" and a decreasing max callid.. but in the end I got the error below. I wonder myself how a message could be "too long" if it's using POST.. or do you still transport the information as GET query, then it would be understandable:

```
An uncaught error was raised while executing job Check Fritzbox
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "C:\Python3\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
  File "C:\workspace\python\fbox\fritzbox-missed-calls-telegram-bot\fritzbotcallinfo\bot.py", line 117, in cb_check_fritzbox
    bot.sendMessage(chat_id=chatId, text=msgtext, parse_mode='Markdown')
  File "<decorator-gen-2>", line 2, in send_message
  File "C:\Python3\lib\site-packages\telegram\bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\telegram\bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "C:\Python3\lib\site-packages\telegram\bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Python3\lib\site-packages\telegram\utils\request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "C:\Python3\lib\site-packages\telegram\utils\request.py", line 244, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
```

But: after retrieving first time a lot of last calls, which seems to break it: the second run it seems to work, I really get new calls posted to the telegram group,

**Comment by bufemc** [comment]
In the console output and in the telegram chat I also get a message at least once: Unknown command '/help'
but for the moment I just ignore it.

I want to give something back: I have seen that you do html parsing for tellows and dastelefonbuch. This is a quite old-fashioned way and will break from time to time. I recently found out (just by guessing) you can just request the tellows information with sth like json=1 - let me re-check my own code.. yes, it's true:

```
http://www.tellows.de/basic/num/{number}?json=1&partner=test&apikey=test123
```

Is this legal? If you don't hit it too often, seems yes, see:
        https://blog.tellows.de/2011/07/tellows-api-fur-die-integration-in-eigene-programme/

**Comment by nitzel** [comment]
Great, I didn't know they had an API.

Re your failure: There's a closed issue [768 at python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot/issues/768) about automatically splitting too long messages but it looks like it's a won't do.

So I'd say: Ignore the error. It should only appear once, aftewards the greatest `callId` should've been persisted to the config file and thus all previous messages ignored. If it's not in the config file, you can try setting it yourself.
**Or** you could add a method to split those messages. Check what `python-telegram-bot`'s `MAX_MESSAGE_LENGTH ` is and if our messages exceed it, split the message. Or define a maximum number of calls to be reported. I don't it's worth much getting a telegram message to your phone specifying 50 different calls, so maybe it could say: `call1, call2, .. call 5. There were 45 more. Type '/get 50' to see the last 50 messages` or so. 

I'm not sure if the `python-telegram-bot` uses `get` or `post`, but would expect it's doing the latter. Did you see an option to change that anywhere?

**Comment by bufemc** [comment]
How do we proceed here, for me it's also fine to close the issue. BTW, recently I also parsed the reverse search for dasOertliche, but it's still no API, but ugly (in that case Javascript was easier) parsing.. I used ```var handlerData = [[ .., .., .. ]]``` - if present, the index 5 is the city and index 14 is the name.

**Comment by nitzel** [comment]
Would be great if you could create a PullRequest for DasÖrtliche. Thanks for your help with improving this repository.
